### ISSUE TITLE
Can't upload code

### ISSUE THREAD

**Issue by ghost** [MediaTek-Labs/aws_mbedtls_mqtt#2]
Hi, after I replace the platform.txt file, I can't upload code with Arduino IDE anymore. 
But if I use the old platform.txt file, everything go well. 

My Arduino IDE is 1.5.7, firmware is 1.1.17.
Thanks.

**Comment by ghost** [comment]
My system is Windows 8.1. Thanks.

**Comment by JasonMTK** [comment]
Hi loovee,

If the original platform.txt is working in your case, that should be fine. The reason for replacing the platfomr.txt file is preventing some unexpected issue like upload failure or no logs show up.

If you find everything working well, then you don't need to replace that file. Just make sure you could upload the sketch successfully and can see the monitor logs as well.

Thanks,

**Comment by ghost** [comment]
Thanks Jason.
